DOCKER_NAMESPACE =	armbuild/
NAME =			ocs-distrib-ubuntu
VERSION =		utopic
VERSION_ALIASES =	14.10
IS_LATEST =		1
TITLE =			Ubuntu Utopic
DESCRIPTION =		Ubuntu Utopic (14.10)
SOURCE_URL =		https://github.com/online-labs/image-ubuntu/tree/master/14.10


## Image tools
all:	docker-rules.mk
docker-rules.mk:
	wget https://raw.githubusercontent.com/online-labs/image-tools/master/docker-rules.mk
-include docker-rules.mk


## Here you can add custom commands and overrides
